create table if not exists assigned_tasks (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  assigned_to_name text not null,
  assigned_to_email text not null,
  assigned_by_name text not null,
  assigned_by_email text not null,
  status text not null default 'pending',
  is_urgent boolean not null default false,
  due_at timestamptz,
  started_at timestamptz,
  completion_notes text,
  -- "Unseen" flags drive the notification dots — false means someone still
  -- needs to see this: assignee_seen goes false when a task is first
  -- assigned, admin_seen goes false when it's completed. Both default true
  -- so backfilled/legacy rows don't suddenly look "new".
  assignee_seen boolean not null default true,
  admin_seen boolean not null default true,
  created_at timestamptz not null default now(),
  completed_at timestamptz
);

create index if not exists assigned_tasks_assigned_to_idx
on assigned_tasks (assigned_to_email);

create index if not exists assigned_tasks_status_idx
on assigned_tasks (status);
