create table if not exists eod_reports (
  id bigint generated by default as identity primary key,
  team_member_email text not null,
  team_member_name text not null,
  report_date date not null default (now() at time zone 'utc')::date,
  status text not null default 'draft',
  submitted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint eod_reports_one_per_person_per_day unique (team_member_email, report_date)
);

create index if not exists eod_reports_email_date_idx
on eod_reports (team_member_email, report_date desc);

create index if not exists eod_reports_date_idx
on eod_reports (report_date desc);

create table if not exists eod_entries (
  id bigint generated by default as identity primary key,
  report_id bigint not null references eod_reports(id) on delete cascade,
  site_name text not null,
  site_domain text,
  site_status text not null,
  page_label text not null,
  page_url text,
  is_new_page boolean not null default false,
  notes text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists eod_entries_report_id_idx
on eod_entries (report_id);

create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists eod_reports_set_updated_at on eod_reports;
create trigger eod_reports_set_updated_at
before update on eod_reports
for each row
execute function set_updated_at();

drop trigger if exists eod_entries_set_updated_at on eod_entries;
create trigger eod_entries_set_updated_at
before update on eod_entries
for each row
execute function set_updated_at();
