create table if not exists manual_review_sites (
  id bigint generated by default as identity primary key,
  site_name text not null unique,
  site_domain text,
  added_by_name text,
  added_by_email text,
  created_at timestamptz not null default now()
);
