alter table website_pages
add column if not exists page_url text;

create table if not exists website_credentials (
  id bigint generated by default as identity primary key,
  website_id bigint not null references websites(id) on delete cascade,
  login_url text,
  username text,
  password text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists website_credentials_website_id_idx
on website_credentials (website_id);

drop trigger if exists website_credentials_set_updated_at
on website_credentials;

create trigger website_credentials_set_updated_at
before update on website_credentials
for each row
execute function set_updated_at();
