-- Bugs found in production, logged by Admin/Manager against the developer
-- responsible — feeds the per-person monthly count shown on /kpis.
create table if not exists production_bugs (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  site_name text,
  site_domain text,
  developer_name text not null,
  developer_email text not null,
  reported_by_name text not null,
  reported_by_email text not null,
  status text not null default 'open',
  fixed_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists production_bugs_developer_email_idx
on production_bugs (developer_email);

create index if not exists production_bugs_created_at_idx
on production_bugs (created_at desc);
