create table if not exists site_reviews (
  id bigint generated by default as identity primary key,
  site_name text not null,
  site_domain text,
  review_period text not null,
  checked_by_name text not null,
  checked_by_email text not null,
  checked_at timestamptz not null default now(),
  constraint site_reviews_one_per_site_per_period unique (site_name, review_period)
);

create index if not exists site_reviews_site_name_idx
on site_reviews (site_name);

create index if not exists site_reviews_site_name_checked_at_idx
on site_reviews (site_name, checked_at desc);
