-- Fixes: "there is no unique or exclusion constraint matching the ON CONFLICT
-- specification" when checking a Site Reviews checklist item.
--
-- supabase/site_reviews.sql was rewritten from the old per-period shape
-- (review_period + unique(site_name, review_period)) to the per-checklist-item
-- shape (unique(site_name, checklist_item)), but that file only ever runs
-- `create table if not exists`, so a database created under the old shape kept
-- its old columns/constraint. The app upserts with
-- onConflict: "site_name,checklist_item", which needs the new constraint.
--
-- This is safe to run repeatedly. If the old per-period table is still in
-- place it is renamed (not dropped) to site_reviews_legacy_periods so the old
-- review history is preserved, and a fresh table with the current schema is
-- created. If the table is already on the new shape it only ensures the
-- unique constraint exists.

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public'
      and table_name = 'site_reviews'
      and column_name = 'review_period'
  ) then
    alter table site_reviews rename to site_reviews_legacy_periods;
    alter index if exists site_reviews_site_name_idx rename to site_reviews_legacy_site_name_idx;
    alter index if exists site_reviews_site_name_checked_at_idx rename to site_reviews_legacy_site_name_checked_at_idx;
  end if;
end $$;

create table if not exists site_reviews (
  id bigint generated by default as identity primary key,
  site_name text not null,
  site_domain text,
  checklist_item text not null,
  checked_by_name text not null,
  checked_by_email text not null,
  checked_at timestamptz not null default now()
);

-- Table already existed on the new shape but without the constraint (e.g. the
-- checklist_item column was added by hand): collapse duplicates first, keeping
-- the most recent check, so the constraint can be added.
delete from site_reviews a
using site_reviews b
where a.site_name = b.site_name
  and a.checklist_item = b.checklist_item
  and (a.checked_at, a.id) < (b.checked_at, b.id);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'site_reviews_one_per_site_per_item'
      and conrelid = 'public.site_reviews'::regclass
  ) then
    alter table site_reviews
      add constraint site_reviews_one_per_site_per_item unique (site_name, checklist_item);
  end if;
end $$;

create index if not exists site_reviews_site_name_idx
on site_reviews (site_name);

create index if not exists site_reviews_site_name_checked_at_idx
on site_reviews (site_name, checked_at desc);
