-- Target schema: one row per (site, checklist item) — no calendar period.
-- A site counts as "reviewed" once every checklist item has a row, and stays
-- reviewed for a rolling 15 days from whenever the last item was checked
-- (i.e. the moment the full set became complete). All of that is computed
-- in the app from checked_at; nothing here needs to encode "which cycle."
create table if not exists site_reviews (
  id bigint generated by default as identity primary key,
  site_name text not null,
  site_domain text,
  checklist_item text not null,
  checked_by_name text not null,
  checked_by_email text not null,
  checked_at timestamptz not null default now(),
  constraint site_reviews_one_per_site_per_item unique (site_name, checklist_item)
);

create index if not exists site_reviews_site_name_idx
on site_reviews (site_name);

create index if not exists site_reviews_site_name_checked_at_idx
on site_reviews (site_name, checked_at desc);
