-- Logs every time a completed task gets sent back for rework. One row per
-- revision event (not per task) so a task can be revised more than once and
-- each round still counts separately for per-person monthly KPIs.
create table if not exists task_revisions (
  id bigint generated by default as identity primary key,
  task_id bigint not null references assigned_tasks(id) on delete cascade,
  task_title text not null,
  -- Whoever was the effective assignee at the moment of revision — the
  -- person who actually has to redo the work, not whoever it was
  -- originally assigned to if it's since been reassigned.
  assignee_name text not null,
  assignee_email text not null,
  requested_by_name text not null,
  requested_by_email text not null,
  reason text not null,
  created_at timestamptz not null default now()
);

create index if not exists task_revisions_task_id_idx
on task_revisions (task_id);

create index if not exists task_revisions_assignee_email_idx
on task_revisions (assignee_email);

create index if not exists task_revisions_created_at_idx
on task_revisions (created_at desc);
