create table website_pages (
  id bigint generated by default as identity primary key,
  website_id bigint not null references websites(id) on delete cascade,
  title text not null,
  status text not null default 'Not Started',
  notes text,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index website_pages_website_id_idx
on website_pages (website_id);

create index website_pages_sort_order_idx
on website_pages (website_id, sort_order);

create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger website_pages_set_updated_at
before update on website_pages
for each row
execute function set_updated_at();
